// Generated by gencpp from file visionmsg/arucotrafficlight.msg
// DO NOT EDIT!


#ifndef VISIONMSG_MESSAGE_ARUCOTRAFFICLIGHT_H
#define VISIONMSG_MESSAGE_ARUCOTRAFFICLIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visionmsg
{
template <class ContainerAllocator>
struct arucotrafficlight_
{
  typedef arucotrafficlight_<ContainerAllocator> Type;

  arucotrafficlight_()
    : distance(0.0)
    , trafficstatus(0)  {
    }
  arucotrafficlight_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , trafficstatus(0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef int16_t _trafficstatus_type;
  _trafficstatus_type trafficstatus;





  typedef boost::shared_ptr< ::visionmsg::arucotrafficlight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visionmsg::arucotrafficlight_<ContainerAllocator> const> ConstPtr;

}; // struct arucotrafficlight_

typedef ::visionmsg::arucotrafficlight_<std::allocator<void> > arucotrafficlight;

typedef boost::shared_ptr< ::visionmsg::arucotrafficlight > arucotrafficlightPtr;
typedef boost::shared_ptr< ::visionmsg::arucotrafficlight const> arucotrafficlightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visionmsg::arucotrafficlight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visionmsg::arucotrafficlight_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visionmsg::arucotrafficlight_<ContainerAllocator1> & lhs, const ::visionmsg::arucotrafficlight_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance &&
    lhs.trafficstatus == rhs.trafficstatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visionmsg::arucotrafficlight_<ContainerAllocator1> & lhs, const ::visionmsg::arucotrafficlight_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visionmsg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::visionmsg::arucotrafficlight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visionmsg::arucotrafficlight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visionmsg::arucotrafficlight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visionmsg::arucotrafficlight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visionmsg::arucotrafficlight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visionmsg::arucotrafficlight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visionmsg::arucotrafficlight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8578ba043a5c5ac07bdb4be2b2a139ea";
  }

  static const char* value(const ::visionmsg::arucotrafficlight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8578ba043a5c5ac0ULL;
  static const uint64_t static_value2 = 0x7bdb4be2b2a139eaULL;
};

template<class ContainerAllocator>
struct DataType< ::visionmsg::arucotrafficlight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visionmsg/arucotrafficlight";
  }

  static const char* value(const ::visionmsg::arucotrafficlight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visionmsg::arucotrafficlight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n"
"int16 trafficstatus\n"
;
  }

  static const char* value(const ::visionmsg::arucotrafficlight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visionmsg::arucotrafficlight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.trafficstatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arucotrafficlight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visionmsg::arucotrafficlight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visionmsg::arucotrafficlight_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "trafficstatus: ";
    Printer<int16_t>::stream(s, indent + "  ", v.trafficstatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISIONMSG_MESSAGE_ARUCOTRAFFICLIGHT_H
